/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TextModel(props) {
  const { nodes, materials } = useGLTF('/E-N2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh castShadow receiveShadow geometry={nodes.Text001.geometry} material={materials.darkgray} />
      <mesh castShadow receiveShadow geometry={nodes.Text001_1.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/E-N2.glb')
